[package]
name = "aici_tokenizers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.107"
aici_abi = { path = "../aici_abi" }
