[workspace]
exclude = ["tch-rs"]
members = [
    "aici_abi",
    "declctrl",
    "aicirt",
    "pyctrl",
    "jsctrl",
    "uppercase",
    "rllm",
    "tch-cuda",
]
resolver = "2"


[profile.release]
debug = 1
