[workspace]
exclude = ["tch-rs"]
members = [
    "aicirt",
    "controllers/aici_abi",
    "controllers/aici_native",
    "controllers/declctrl",
    "controllers/pyctrl",
    "controllers/jsctrl",
    "controllers/guidance_ctrl",
    "controllers/ag2_ctrl",
    "controllers/ag2_tester",
    "controllers/uppercase",
    "rllm/rllm-base",
    "rllm/rllm-cuda",
    "rllm/rllm-llamacpp",
    "rllm/tch-cuda",
    "rllm/llama-cpp-low"
]
resolver = "2"

[profile.release]
debug = 1
