[workspace]
exclude = ["tch-rs"]
members = [
    "aici_abi",
    "aici_ast_runner",
    "aici_tokenizers",
    "aicirt",
    "pyvm",
    "rllm",
    "tch-cuda",
]
resolver = "2"


[profile.release]
debug = 1
