[workspace]
exclude = ["tch-rs"]
members = [
    "aicirt",
    "controllers/aici_abi",
    "controllers/aici_native",
    "controllers/pyctrl",
    "controllers/jsctrl",
    "controllers/guidance_ctrl",
    "controllers/guidance_parser",
    "controllers/uppercase",
    "rllm/rllm-base",
    "rllm/rllm-cuda",
    "rllm/rllm-llamacpp",
    "rllm/tch-cuda",
    "rllm/llama-cpp-low",
    "py/guidance/guidance/_rust",
]
resolver = "2"

[profile.release]
debug = 1
