[package]
name = "infer"
version = "0.1.0"
edition = "2021"


[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.3.1", features = ["cuda", "cudnn"] }

[[bin]]
name = "infer"
path = "src/infer.rs"
