[package]
name = "gvm_tokenizers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
gvm_abi = "0.1.0"

[patch.crates-io]
gvm_abi = { path = "../gvm_abi" }
